steps:
- name: 'golang:1.19'
  id: 'Run tests'
  env: ['GO111MODULE=on', 'LOG_LEVEL=1', 'LOG_FILE=mylog.log', 'GITHUB_TOKEN=${_GITHUB_TOKEN}']
  args: ['go', 'test', './...']

- name: 'gcr.io/cloud-builders/docker'
  id: build_docker_image
  entrypoint: 'bash'
  args: ['build', '-t', 'gcr.io/trusted-package-registry/team24:$SHORT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/trusted-package-registry/team24:$SHORT_SHA']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'team24'
  - '--image'
  - 'gcr.io/trusted-package-registry/team24:$SHORT_SHA'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'

