name: run-commands
run-name: ${{ github.actor }} is trying to integrate
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint with Go fmt
        run: gofmt -w -s .

  autograde-commands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run install
        run: ./run install
      - name: Run build
        run: ./run build
      - name: Run Test
        run: ./run test
      - name: Set env
        run: echo "ABSFILEPATH=$(readlink -f test/urls_file.txt)" >> $GITHUB_ENV
      - name: Run URL_FILE
        run: ./run "${ABSFILEPATH}"
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint-js:
    runs-on: ubuntu-latest
    name: Run ESLint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install NPM packages
        run: cd frontend/my-app/ && npm install

      - name: Lint
        run: cd frontend/my-app/ && npm run lint

      # - name: Check formatting
      #   run: cd frontend/my-app/ && npm run prettier-check
